version: '3'
services:
  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
  golang-project-a:
    image: golang-project-a:latest
    ports:
      - "8080:8080"
    depends_on:
      - "mongo"