// Code generated by MockGen. DO NOT EDIT.
// Source: github.com/adityarev/go-be-starter-2/pkg/core/adapter/permissionadapter (interfaces: RepoAdapter)

// Package mock_permissionadapter is a generated GoMock package.
package mock_permissionadapter

import (
	context "context"
	permissionadapter "twatter/pkg/core/adapter/permissionadapter"
	domain "twatter/pkg/core/domain"
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
)

// MockRepoAdapter is a mock of RepoAdapter interface
type MockRepoAdapter struct {
	ctrl     *gomock.Controller
	recorder *MockRepoAdapterMockRecorder
}

// MockRepoAdapterMockRecorder is the mock recorder for MockRepoAdapter
type MockRepoAdapterMockRecorder struct {
	mock *MockRepoAdapter
}

// NewMockRepoAdapter creates a new mock instance
func NewMockRepoAdapter(ctrl *gomock.Controller) *MockRepoAdapter {
	mock := &MockRepoAdapter{ctrl: ctrl}
	mock.recorder = &MockRepoAdapterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockRepoAdapter) EXPECT() *MockRepoAdapterMockRecorder {
	return m.recorder
}

// Create mocks base method
func (m *MockRepoAdapter) Create(arg0 context.Context, arg1 permissionadapter.RepoCreate) (domain.Permission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", arg0, arg1)
	ret0, _ := ret[0].(domain.Permission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create
func (mr *MockRepoAdapterMockRecorder) Create(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockRepoAdapter)(nil).Create), arg0, arg1)
}

// Delete mocks base method
func (m *MockRepoAdapter) Delete(arg0 context.Context, arg1 uint32) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", arg0, arg1)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete
func (mr *MockRepoAdapterMockRecorder) Delete(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockRepoAdapter)(nil).Delete), arg0, arg1)
}

// Find mocks base method
func (m *MockRepoAdapter) Find(arg0 context.Context, arg1 uint32) (domain.Permission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Find", arg0, arg1)
	ret0, _ := ret[0].(domain.Permission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Find indicates an expected call of Find
func (mr *MockRepoAdapterMockRecorder) Find(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Find", reflect.TypeOf((*MockRepoAdapter)(nil).Find), arg0, arg1)
}

// GetList mocks base method
func (m *MockRepoAdapter) GetList(arg0 context.Context, arg1 permissionadapter.RepoFilter) (domain.Permissions, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetList", arg0, arg1)
	ret0, _ := ret[0].(domain.Permissions)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetList indicates an expected call of GetList
func (mr *MockRepoAdapterMockRecorder) GetList(arg0, arg1 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetList", reflect.TypeOf((*MockRepoAdapter)(nil).GetList), arg0, arg1)
}

// Update mocks base method
func (m *MockRepoAdapter) Update(arg0 context.Context, arg1 uint32, arg2 permissionadapter.RepoUpdate) (domain.Permission, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", arg0, arg1, arg2)
	ret0, _ := ret[0].(domain.Permission)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Update indicates an expected call of Update
func (mr *MockRepoAdapterMockRecorder) Update(arg0, arg1, arg2 interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockRepoAdapter)(nil).Update), arg0, arg1, arg2)
}
